name: Disable Checking ServerName

on:
  workflow_dispatch:
  push:
    branches:
      - main
  pull_request:
    branches: [ main ]
  pull_request_target:
    types: [assigned, opened, synchronize, reopened]

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          submodules: true

      - name: modify
        run: |
          cd tailscale
          sed -i '/hi.ServerName != m.hostname/,+2d' cmd/derper/cert.go

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v1

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1
          
      - name: Login to ghcr.io
        uses: docker/login-action@v2
        with:
          registry: ghcr.io
          username: ${{ github.repository_owner }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Generate version tags
        id: meta
        run: |
          echo "sha_short=$(git rev-parse --short HEAD)" >> $GITHUB_OUTPUT
          echo "date=$(date +%Y%m%d)" >> $GITHUB_OUTPUT
          echo "version=$(date +%Y%m%d)-$(git rev-parse --short HEAD)" >> $GITHUB_OUTPUT

      - name: Generate changelog
        id: changelog
        run: |
          cd tailscale
          TAILSCALE_VERSION=$(git describe --tags --abbrev=0 2>/dev/null || echo "unknown")
          echo "tailscale_version=$TAILSCALE_VERSION" >> $GITHUB_OUTPUT
          
          # Get recent commits from Tailscale
          CHANGELOG=$(git log --pretty=format:"- %s (%h)" -n 20 || echo "No recent changes")
          
          # Save to file
          cat > ../release_notes.md << 'EOF'
## Tailscale DERP Server Build

EOF
          cat >> ../release_notes.md << EOF
**Tailscale Version**: $TAILSCALE_VERSION
**Build Date**: $(date +%Y-%m-%d)
**Commit**: $(cd .. && git rev-parse HEAD)

### Recent Tailscale Changes
$CHANGELOG

### Modifications
- Removed ServerName validation in cert.go for IP address support
- Added automatic IP SAN generation in certificates
EOF
          
          cat ../release_notes.md

      # Runs a single command using the runners shell
      - name: Build and push Docker images to docker.io and ghcr.io
        if: github.event_name == 'push' && github.ref == 'refs/heads/main'
        uses: docker/build-push-action@v2
        with:
          file: 'Dockerfile'
          platforms: linux/amd64,linux/arm64
          context: ./
          push: true
          tags: |
            ghcr.io/0xrichardh/ip_derper:latest
            ghcr.io/0xrichardh/ip_derper:${{ steps.meta.outputs.date }}-${{ steps.meta.outputs.sha_short }}

      - name: Create Release
        if: github.event_name == 'push' && github.ref == 'refs/heads/main'
        uses: softprops/action-gh-release@v1
        with:
          tag_name: v${{ steps.meta.outputs.version }}
          name: Release v${{ steps.meta.outputs.version }}
          body_path: release_notes.md
          draft: false
          prerelease: false
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
