name: Disable Checking ServerName

on:
  workflow_dispatch:
  push:
    branches:
      - main
  pull_request:
    branches: [ main ]
  pull_request_target:
    types: [assigned, opened, synchronize, reopened]

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          submodules: true

      - name: modify
        run: |
          # sed -i '/hi.ServerName != m.hostname/,+2d' cmd/derper/cert.go
          ls -lh
